---
abstract: 'show Apache-style directory listings in your Mojolicious app'
author:
  - "Marty O'Brien <mob@cpan.org>"
build_requires:
  Test::Mojo: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoX-DirectoryListing
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious::Lite: 0
  perl: 5.01
version: 0.01
